# Copyright 2026 Lars Hermges @l3montree GMBH

name: Documentation Policy Check
on:
  pull_request:
  workflow_call:
    inputs:
      documentation_repo:
        required: true
        type: string
      production_repo:
        required: true
        type: string
      policy_url:
        required: true
        type: string
      json_path:
        required: false
        type: string

jobs:
  documentation_check:
    uses: ./.github/workflows/docu-policy.yml
    with:
      documentation_repo: ${{ inputs.documentation_repo }}
      production_repo: ${{ inputs.production_repo }}
      policy_url: ${{ inputs.policy_url }}
      json_path: ${{ inputs.json_path }}