# Copyright 2026 Lars Hermges @l3montree GMBH

name: Documentation Policy Check
on:
  pull_request

jobs:
  documentation_check:
    uses: ./.github/workflows/attestor.yaml
    with:
      documentation-repo: ${{ inputs.documentation-repo }}
      production-repos: ${{ inputs.production-repo}}

