# Copyright 2026 Lars Hermges @l3montree GMBH

name: Documentation Policy Check
on:
  pull_request:
  workflow_call:
    inputs:
      documentation-repo:
        required: true
        type: string
      production-repos:
        required: true
        type: string

jobs:
  documentation_check:
    uses: ./.github/workflows/attestor.yml
    with:
      documentation-repo: ${{ inputs.documentation-repo }}
      production-repos: ${{ inputs.production-repos}}
